### PR TITLE
PR: More Robust Server Error Handling

### LINKED ISSUE #21: More Robust Server Error Handling
I was checking the entire flow of how new people perceive our site, and our developer onboarding flow through dao.ubq.fi/devpool etc as I do regularly these days (to ensure seamless onboarding!) and realized that work.ubq.fi only rendered nine tasks. 
work ubq fi_ (1)

I was quick to assume I got rate limited but realized that there indeed are only nine tasks open in the devpool-directory "backend"

Fortunately GitHub Actions has logs and I was able to discover

> [Getting ubiquity org repositories failed: HttpError: Server Error](https://github.com/ubiquity/devpool-directory/actions/runs/8259431257/job/22593325855#step:7:12)

This is a problem because it actually closes all the issues when this occurs! 

The script should be smart enough to ignore the @ubiquity org tasks in this situation in case there are 5xx level errors!

### PR DESCRIPTION
**Pull request by EresDev**
Resolves https://github.com/ubiquity/devpool-directory-bounties/issues/21

It turned out try/catch isn't always a good idea. When the "Sync Issues" action failed, it was showing the action passed, with green tick. 
https://github.com/ubiquity/devpool-directory/actions/runs/8259431257/job/22593325855#step:7:12

Letting the error propagate was the solution. No try/catch in main function. Let it return to the action as a failure. Also, when the most important parts of the code throw an error, the error propagates and no more steps are performed in the code, where closing the issues is the last step. 

Here is a QA for failure. What happens if there is 404, timeout, rate limit, or other errors? Sync issue fails, shows clear failure in Github actions, and the error log shows complete details. Even though this is a 404 error, you can also see rate limit details in the error logs that come with all requests. 
https://github.com/EresDevOrg/devpool-directory-qa/actions/runs/8361911852/job/22891165425#step:7:18

QA with success: https://github.com/EresDevOrg/devpool-directory-qa/actions/runs/8362787261/job/22894236651

Attention must be given to merge. A merge to production can reveal other problems that were previously hidden due to the false positive nature of the Sync Issues action.

### CODE REVIEW

File: helpers/github.ts [hunk 1]
```diff
@@ -112,6 +113,7 @@ export async function getRepoUrls(orgOrRepo: string) {
         } else console.warn(`Getting repo ${params[0]}/${params[1]} failed: ${res.status}`);
       } catch (e: unknown) {
         console.warn(`Getting repo ${params[0]}/${params[1]} failed: ${e}`);
+        throw e;
```
Comment (0x4007) [inline helpers/github.ts]:
```suggestion
        throw error;
```

Comment (EresDev) [reply helpers/github.ts]: Done in a new commit. Rename was needed in at least 2 places.

**Comment by 0x4007** [comment]
As a heads up I've transitioned out of full time coding since 1 March to focus on our fundraising and recruiting efforts. Because of this I can't be the main reviewer and merger, but I think you can ping @rndquu to get oriented on new repositories but generally there are certain team members that lead certain repositories which you'll pick up on after working on them enough.

**Review by 0x4007 — APPROVED** [review]
Code looks fine but won't have a chance to test.

**Comment by gitcoindev** [comment]
I went through the changes. Was wondering about reverting silencing stderr done in https://github.com/ubiquity/devpool-directory/commit/e4b8dfa601f423ed1e2f8d57b6f9b0126faabe98 , but overall looks safe to merge.

**Review by gitcoindev — APPROVED** [review]

**Comment by EresDev** [comment]
> I went through the changes. Was wondering about reverting silencing stderr done in [e4b8dfa](https://github.com/ubiquity/devpool-directory/commit/e4b8dfa601f423ed1e2f8d57b6f9b0126faabe98) , but overall looks safe to merge.

Errors were hiding behind it. There was a 404 error that was not being reported because of the console.warn mock.
